project:
  type: website
  preview:
    port: 7777
    browser: false
  render:
    - "*.qmd"

website:
  title: "gyan's sight"
  favicon: images/favicon_lncumn.ico
  navbar:
    toggle-position: right
    # pinned: true
    collapse-below: xxl
    left:
      - href: index.qmd
        text: Home
      - about.qmd

      - content/DynamicsSimulations/index.qmd
      - content/Resources/index.qmd
      - content/Blog/index.qmd
  sidebar:
    - id: dynamics
      search: true
      contents: DynamicsSimulations
      alignment: left

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

    header-includes: |
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fontsource/iosevka/index.css">
      <script>
        document.addEventListener('DOMContentLoaded', () => {
          const maxScroll = 300;

          const updateOverlayOpacity = () => {
            const scrollY = Math.min(window.scrollY, maxScroll);
            const opacity = (scrollY / maxScroll).toFixed(2);
            document.documentElement.style.setProperty('--overlay-opacity', opacity);
          };

          updateOverlayOpacity();
          window.addEventListener('scroll', updateOverlayOpacity, { passive: true });
        });
      </script>

    # code-overflow: wrap
    # code-line-numbers: true
