project:
  type: website
  preview:
    port: 7777
    browser: false
  render:
    - "*.qmd"
    - "clones/DynamicsSimulations/README.md"
    - "clones/DynamicsSimulations/problem01/README.md"
    - "clones/DynamicsSimulations/problem02/README.md"
    - "clones/DynamicsSimulations/problem03/README.md"
    - "clones/DynamicsSimulations/problem04/README.md"
    - "clones/DynamicsSimulations/problem05/README.md"
    - "clones/DynamicsSimulations/problem06/README.md"
    - "clones/DynamicsSimulations/problem07/README.md"
    - "clones/DynamicsSimulations/problem08/README.md"
    - "clones/DynamicsSimulations/problem09/README.md"
    - "clones/DynamicsSimulations/problem10/README.md"
    - "clones/DynamicsSimulations/problem11/README.md"
    - "clones/DynamicsSimulations/problem12/README.md"
    - "clones/DynamicsSimulations/problem13/README.md"
    - "clones/DynamicsSimulations/problem14/README.md"
    - "clones/DynamicsSimulations/problem15/README.md"

website:
  title: "vishal's sight"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: clones/DynamicsSimulations/README.md
        text: Dynamics

format:
  html:
    theme:
      - cosmo
      - brand
      # - sketchy
      # - pandoc
      # - litera
    css: styles.css
    toc: true

    header-includes: |
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fontsource/iosevka/index.css">
    # code-overflow: wrap
    code-line-numbers: true
