project:
  type: website
  preview:
    port: 7777
    browser: false
  render:
    - "*.qmd"

website:
  title: "gyan's sight"
  favicon: media/favicon_lncumn.ico
  site-url: https://haxfn.github.io/meta-site/

  navbar: false
    # toggle-position: right
    # pinned: true
    # collapse-below: xxl
    # left:
    #   - href: index.qmd
    #     text: Home
    #   - content/DynamicsSimulations/index.qmd
    #   - content/Resources/index.qmd
    #   - content/Blog/index.qmd
    # right:
    #   - href: content/Blog/index.xml
    #     icon: rss

  reader-mode: true
  sidebar:
    - id: gyan
      href: https://github.com/haxfn
      contents: content

    - id: dynamics
      title: <a href="/content/DynamicsSimulations/">Dynamics and Simulations</a>
      # logo: content/DynamicsSimulations/media/problem05/ruina-pratap-cover.jpg
      # logo-href: /content/DynamicsSimulations/index.qmd

      contents: content/DynamicsSimulations/
      tools:
        - icon: github
          href: https://github.com/gyanantaran/DynamicsSimulations

    - id: resources
      contents: content
      tools:
        - icon: github
          href: https://github.com/mangoqualitee/Resources

format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: media/css/styles.css
    toc: true
    callout-collapsed: true
    callout-appearance: simple

#    include-in-header:
#      - file: panel.qmd
    header-includes: |
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fontsource/iosevka/index.css">
      <script>
        document.addEventListener('DOMContentLoaded', () => {
          const maxScroll = 300;

          const updateOverlayOpacity = () => {
            const scrollY = Math.min(window.scrollY, maxScroll);
            const opacity = (scrollY / maxScroll).toFixed(2);
            document.documentElement.style.setProperty('--overlay-opacity', opacity);
          };

          updateOverlayOpacity();
          window.addEventListener('scroll', updateOverlayOpacity, { passive: true });
        });
      </script>

    # code-overflow: wrap
    # code-line-numbers: true

filters:
  - media/filters/callout.lua
